//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoGráfico
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRAFICO_RC
    {
        public int ID { get; set; }
        public string VALOR_CAPACITOR { get; set; }
        public string VALOR_RESISTOR { get; set; }
        public string TEMPO { get; set; }
        public string EDO { get; set; }
        public string Vc_INICIAL { get; set; }
        public string V_FONTE { get; set; }
    }
}
